### ISSUE TITLE
Safari seems to render with visual artifacts

### ISSUE THREAD

**Issue by MelMacaluso** [propjockey/augmented-ui#13]
Hi there, thanks for the great lib, loving it so far!

We develop our full project around it and it really gives a nice touch with ease. When we tried it on Safari thought it seemed to render with some unwanted effects. 

I tried to remove all the other CSS that might interfere with it to no avail. 

(the website in question: https://hirex-game.io/)

Actual wanted result on chrome and firefox:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/24974216/169505821-42634ed7-dd63-4393-8ccb-8e61b111d237.png">

Visual artifacts with Safari:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/24974216/169505954-68e1e654-bce5-4948-8d78-9a79d82512cb.png">

I tried to inspect one by one the CSS variables and as mentioned removing all possible interfering CSS but nothing worked.

Tried the CDN and Module version but nothing so far...

Any help would be greatly appreciated! Thank you!

ps: @JaneOri I added you on discord too if you want to chat over there too.

**Comment by JaneOri** [comment]
Just saw this sorry for the delay. Looks awesome though!!

You need an element wrapping the h and r icons with the attribute **data-augmented-ui-reset** since augmented elements need a separate reset layer wrapping the nested augmented elements pre housini spec

You can ctrl f in the docs to see why but that will fix it!
