### ISSUE TITLE
Is it possible to make this compatible with drop shadow?

### ISSUE THREAD

**Issue by AramZS** [propjockey/augmented-ui#7]
Hi, first I just wanted to say this is great work, the library is amazing and very well documented. So many cool little features that are fun to play with. 

I was hoping that I could use `box-shadow` with some of the elements created with the library (I'm using the additional `splice` script in order to make it work with nth-of-type css logic) and I was hoping to have some sort of drop shadow effect applied to some of the elements, but it keeps disappearing on load. I'm assuming this is because some of the effects use the box-shadow feature? But I'm not sure. I was wondering if there was any way to create a drop shadow effect using the tools in the library. If not, can I add that as a future feature request? 

Thanks!

**Comment by James0x57** [comment]
Hello @AramZS ! 

Really glad you're enjoying it and diving into the details!

box-shadow doesn't show up because the element is masked with clip-path to give it the shape so you can't see any overflow including box-shadow

BUT good news, if you wrap your augmented element in a container, you can use CSS filter box-shadow to do almost the exact same thing
![image](https://user-images.githubusercontent.com/7545075/87260908-c1384a00-c479-11ea-95fc-2e03f613588e.png)

The extra dom sucks (unless they're already in a list container) but the results are pretty decent:
![image](https://user-images.githubusercontent.com/7545075/87260866-8cc48e00-c479-11ea-9a00-30c109fcedbd.png)

Here's a jsbin with full example code:
https://jsbin.com/wurebapepi/edit?html,css,output

Hope this helps!
I'm going to close this but feel free to comment, re-open, or post a new issue if you need anything else!

🍻 
//James

**Comment by James0x57** [comment]
I just realized what you meant with nth-of-type too. That's a solid reason to change augs from the CSS. Good thinking!

I'm definitely going to use that as an example for v2 (augs in v2 core can be equipped from CSS without a script!) Thank you!
